CREATE TABLE `t_paciente` (
  `patient_id` int(11) NOT NULL DEFAULT '0',
  `provider_id` int(11) NOT NULL DEFAULT '0', 
  `location_id` int(11) NOT NULL DEFAULT '0',
  `hdd` varchar(255) DEFAULT NULL,
  `dataabertura` datetime DEFAULT NULL,
  `nid` varchar(255) DEFAULT NULL,
  `nome` varchar(255) DEFAULT NULL,
  `apelido` varchar(255) DEFAULT NULL,
  `sexo` varchar(255) DEFAULT NULL,
  `datanasc` date DEFAULT NULL,
  `idade` int(11) DEFAULT NULL,
  `meses` int(11) DEFAULT NULL,
  `tipopaciente` varchar(255) DEFAULT NULL,
  `identificacao` varchar(255) DEFAULT NULL,  
  `codfuncionario` varchar(255) DEFAULT NULL,
  `avenida` varchar(255) DEFAULT NULL,
  `celula` varchar(255) DEFAULT NULL,
  `codbairro` varchar(255) DEFAULT NULL,
  `coddistrito` varchar(255) DEFAULT NULL,
  `codregime` varchar(255) DEFAULT NULL,
  `cirurgias` varchar(255) DEFAULT NULL,
  `transfusao` varchar(255) DEFAULT NULL,  
  `estadiooms` varchar(255) DEFAULT NULL,      
  `codproveniencia` varchar(255) DEFAULT NULL,
  `designacaoprov` varchar(255) DEFAULT NULL,
  `codigoproveniencia` varchar(255) DEFAULT NULL,
  `emtarv` tinyint(4) DEFAULT NULL,
  `datainiciotarv` date DEFAULT NULL,
  `codestado` varchar(255) DEFAULT NULL,
  `destinopaciente` varchar(255) DEFAULT NULL,
  `datasaidatarv` date DEFAULT NULL,
  `datadiagnostico` date DEFAULT NULL,
  `aconselhado` tinyint(4) DEFAULT NULL,
  `referidohdd` varchar(255) DEFAULT NULL,
  `datareferidohdd` varchar(255) DEFAULT NULL,
  `aceitabuscaactiva` varchar(255) DEFAULT NULL,
  `dataaceitabuscaactiva` date DEFAULT NULL,
  `referidobuscaactiva` varchar(255) DEFAULT NULL,
  `datareferenciabuscaactiva` date DEFAULT NULL,
  `situacaohiv` varchar(255) DEFAULT NULL,
  `observacao` varchar(255) DEFAULT NULL,
  `patientID` varchar(255) DEFAULT NULL,
  emtratamentotb tinyint(1) default 0,
  PRIMARY KEY (`patient_id`),
  UNIQUE KEY `nidUnique` (`nid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;